services:
  - type: web
    name: face-attendance-streamlit
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libgl1-mesa-glx
      pip install -r requirements.txt
    startCommand: streamlit run app.py
